spring:
  application:
    name: super-ai-agent
  profiles:
    active: local

server:
  port: 8123
  servlet:
    context-path: /api

# 接口文档
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yy.superaiagent.controller
# knife4j 高级配置
knife4j:
  enable: true
  setting:
    language: zh_cn
